a1 = input('Digite Algo')
print('O tipo primitivo deste valor é',type(a1))
print('Tem somente espaços?',a1.isspace())
print('É um numero?',a1.isalnum())
print('É alfabetico?',a1.isalpha())
print('É alfanumérico?',a1.isalnum())
print('Está em maiusculo?',a1.isupper())
print('Está em minusculo?',a1.islower())
print('Está capitalizada?',a1.istitle())
